# Generated by Django 6.0.3 on 2026-03-06 16:35

import datetime
import django.contrib.gis.db.models.fields
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from django.db import migrations, models


def combine_fields(apps, schema_editor):
    Campaign = apps.get_model('campaigns', 'Campaign')
    for campaign in Campaign.objects.all():
        if campaign.materials_url:
            link_html = f'<p><a href="{campaign.materials_url}" target="_blank">Campaign Materials</a></p>'
            if campaign.instructions:
                campaign.instructions = f'<p>{campaign.instructions}</p>{link_html}'
            else:
                campaign.instructions = link_html
            campaign.save()


def fold_goal_into_instructions(apps, schema_editor):
    Campaign = apps.get_model('campaigns', 'Campaign')
    for campaign in Campaign.objects.all():
        if campaign.goal:
            goal_html = f'<p><strong>Goal:</strong> {campaign.goal}</p>'
            if campaign.instructions:
                campaign.instructions = goal_html + campaign.instructions
            else:
                campaign.instructions = goal_html
            campaign.save()

class Migration(migrations.Migration):

    replaces = [('campaigns', '0001_initial'), ('campaigns', '0002_alter_street_unique_together_street_block_index_and_more'), ('campaigns', '0003_campaign_map_error'), ('campaigns', '0004_campaign_bbox'), ('campaigns', '0005_merge_materials_into_instructions'), ('campaigns', '0006_remove_goal_fold_into_instructions'), ('campaigns', '0007_add_addr_range_to_street'), ('campaigns', '0008_cityfetchjob_street_city_index'), ('campaigns', '0009_trip_deleted'), ('campaigns', '0010_remove_street_addr_from_remove_street_addr_to'), ('campaigns', '0011_campaign_streets_geojson')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('goal', models.TextField()),
                ('cities', models.JSONField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('materials_url', models.URLField(blank=True)),
                ('contact_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('map_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map_error', models.TextField(blank=True, default='')),
                ('bbox', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('name', models.CharField(blank=True, max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='campaigns.campaign')),
                ('block_index', models.PositiveSmallIntegerField(default=0)),
                ('end_node_id', models.BigIntegerField(blank=True, null=True)),
                ('start_node_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('campaign', 'osm_id', 'block_index')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('worker_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='campaigns.campaign')),
                ('streets', models.ManyToManyField(to='campaigns.street')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.RunPython(
            code=combine_fields,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='materials_url',
        ),
        migrations.RunPython(
            code=fold_goal_into_instructions,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='goal',
        ),
        migrations.AddField(
            model_name='street',
            name='city_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CityFetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_index', models.IntegerField()),
                ('city_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_fetch_jobs', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['city_index'],
                'unique_together': {('campaign', 'city_index')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='streets_geojson',
            field=models.TextField(blank=True, default=''),
        ),
    ]
