# Generated by Django 6.0.2 on 2026-03-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='street',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='street',
            name='block_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='street',
            name='end_node_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='start_node_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='street',
            unique_together={('campaign', 'osm_id', 'block_index')},
        ),
    ]
