# Generated by Django 6.0.2 on 2026-03-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_geo_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='map_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('warning', 'Warning'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
