# Generated by Django 6.0.2 on 2026-03-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_map_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='bbox',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
