# Generated by Django 6.0.2 on 2026-03-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='map_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Fetching'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('warning', 'Warning'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cityfetchjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Fetching'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
