# Generated by Django 6.0.2 on 2026-03-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_goal_fold_into_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='addr_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='addr_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
