# Generated by Django 6.0.3 on 2026-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_decouple_streets_from_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cached_size_household_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cached_size_street_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
