# Generated by Django 6.0.3 on 2026-03-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_trip_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='addr_from',
        ),
        migrations.RemoveField(
            model_name='street',
            name='addr_to',
        ),
    ]
