# Generated by Django 6.0.3 on 2026-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_fix_mysql_email_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
