# Generated by Django 6.0.4 on 2026-04-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_cities_default_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='worker_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
