# Generated by Django 6.0.4 on 2026-04-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_add_worker_email_to_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='access_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
