# Generated by Django 6.0.4 on 2026-04-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_add_access_code_to_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('trip_logged', 'Trip Logged'), ('access_code_attempt', 'Access Code Attempt')], db_index=True, max_length=50)),
                ('campaign_slug', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('method', models.CharField(default='', max_length=10)),
                ('status_code', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
