# Generated by Django 6.0.4 on 2026-04-29 22:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_add_usageevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('coverage', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('license', models.CharField(blank=True, default='', max_length=200)),
                ('attribution', models.TextField(blank=True, default='')),
                ('adapter_type', models.CharField(choices=[('upload', 'User upload')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_region_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('parent_admin_area', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='campaigns.regionsource')),
            ],
            options={
                'ordering': ['source', 'name'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='campaigns_region_src_ext_idx')],
            },
        ),
    ]
